coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        paths: 
          - "torchseq"
    patch:
      default:
        target: 5%
ignore:
  - ".aqenv/*"
  - "torchseq/args.py"
  - "torchseq/main.py"
  - "torchseq/metric_hooks/*"
  - "torchseq/utils/config_migration.py"